df <- read.table("household_power_consumption.txt",sep=";",na.strings="?",header=TRUE,colClasses = c('character', 'character', 'numeric','numeric', 'numeric', 'numeric','numeric', 'numeric', 'numeric'),)   
df$DateTime <- strptime(paste(df$Date, df$Time), "%d/%m/%Y %H:%M:%S")
df <- df[as.Date(df$DateTime)==as.Date("2007-02-01") | as.Date(df$DateTime) == as.Date("2007-02-02"), ]
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(df$DateTime, df$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(df$DateTime, df$Voltage, xlab="datetime", ylab="Voltage", type="l")
plot(df$DateTime, df$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(df$DateTime, df$Sub_metering_2, type="l", col="red")
lines(df$DateTime, df$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, lwd=1, col=c("black","blue","red"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(df$DateTime, df$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l") 
dev.off()